# Generated by Django 4.2.7 on 2023-12-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='info',
        ),
    ]
